// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CheckResult struct {
	ID         string
	MonitorID  string
	StatusCode int32
	LatencyMs  int32
	Error      pgtype.Text
	CheckedAt  time.Time
}

type Monitor struct {
	ID             string
	Url            string
	IntervalSec    int32
	ExpectedStatus int32
	CreatedAt      time.Time
}
