// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Monitor struct {
	ID             string
	Url            string
	IntervalSec    int32
	ExpectedStatus int32
	CreatedAt      time.Time
}
