// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitor.sql

package db

import (
	"context"
	"time"
)

const createMonitor = `-- name: CreateMonitor :exec
INSERT INTO monitors (id, url, interval_sec, expected_status, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateMonitorParams struct {
	ID             string
	Url            string
	IntervalSec    int32
	ExpectedStatus int32
	CreatedAt      time.Time
}

func (q *Queries) CreateMonitor(ctx context.Context, arg CreateMonitorParams) error {
	_, err := q.db.Exec(ctx, createMonitor,
		arg.ID,
		arg.Url,
		arg.IntervalSec,
		arg.ExpectedStatus,
		arg.CreatedAt,
	)
	return err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
DELETE FROM monitors
WHERE id = $1
`

func (q *Queries) DeleteMonitor(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMonitor, id)
	return err
}

const getMonitorByID = `-- name: GetMonitorByID :one
SELECT id, url, interval_sec, expected_status, created_at
FROM monitors
WHERE id = $1
`

func (q *Queries) GetMonitorByID(ctx context.Context, id string) (Monitor, error) {
	row := q.db.QueryRow(ctx, getMonitorByID, id)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.IntervalSec,
		&i.ExpectedStatus,
		&i.CreatedAt,
	)
	return i, err
}

const listMonitors = `-- name: ListMonitors :many
SELECT id, url, interval_sec, expected_status, created_at
FROM monitors
ORDER BY created_at DESC
`

func (q *Queries) ListMonitors(ctx context.Context) ([]Monitor, error) {
	rows, err := q.db.Query(ctx, listMonitors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.IntervalSec,
			&i.ExpectedStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
